
server:
  port: 8081

spring:
  profiles: default
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        event-in:
          group: product
          destination: shop
          contentType: application/json
        event-out:
          destination: shop
          contentType: application/json
---
hystrix:
  command:
    # 전역설정
    default:
      execution.isolation.thread.timeoutInMilliseconds: 610
server:
  port: 8080

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
      bindings:
        event-in:
          group: paymentmanagement
          destination: eventTopic
          contentType: application/json
        event-out:
          destination: eventTopic
          contentType: application/json
